import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  select: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    height: '48px',
    marginBottom: '20px',
    paddingLeft: '12px',
    paddingRight: '4px',
    paddingVertical: '5px',
    boxSizing: 'border-box',
    border: '1px solid #666666',
    transition: '0.5s',
    outlineStyle: 'none',
    borderRadius: '10px',
    color: '#000000',
    backgroundColor: '#FFFFFF',
  },
  selectContainer: {
    position: 'absolute',
    left: '0px',
    width: '100%',
    paddingHorizontal: '12px',
    paddingVertical: '5px',
    boxSizing: 'border-box',
    border: '1px solid #666666',
    transition: '0.5s',
    outlineStyle: 'none',
    borderRadius: '10px',
    color: '#000000',
    backgroundColor: '#eeeeee',
  },
  text: {
    width: '100%',
    height: '100%',
    fontSize: '20px',
    fontWeight: '400',
    marginHorizontal: '12px',
    backgroundColor: 'transparent',
    border: '0px solid',
    outlineStyle: 'none',
    placeholderTextColor: '#AAAAAA',
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: '#00000011',
  }
})